FROM ubuntu:lastest AS build

RUN apt-get update
RUN apt-get install openjdk-17-jdk -y

COPU . .

RUN apt-get install maven -y
RUN mvn clean install

EXPOSE 8080

COPY --from=build /target/TodolistApplication app.jar

ENTRYPOINT ["java", "-jar","app.jar"]